<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HousesTableSeeder extends Seeder
{
    public function run()
    {
        // Insert sample house data
        DB::table('houses')->insert([
            [
                'Address' => '123 Main Street',
                'Type' => 'Apartment',
                'NumberOfRoom' => 3,
                'NumberOfToilet' => 2,
                'NumberOfBelcony' => 1,
                'Rent' => 1500,
                'Image' => 'house1.jpg',
                'Status' => 'available',
                'Location' => 'City Center',
                'UserID' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '456 Oak Avenue',
                'Type' => 'House',
                'NumberOfRoom' => 4,
                'NumberOfToilet' => 3,
                'NumberOfBelcony' => 2,
                'Rent' => 2000,
                'Image' => 'house2.jpg',
                'Status' => 'available',
                'Location' => 'Suburb',
                'UserID' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '789 Pine Street',
                'Type' => 'Condo',
                'NumberOfRoom' => 2,
                'NumberOfToilet' => 1,
                'NumberOfBelcony' => 1,
                'Rent' => 1200,
                'Image' => 'house3.jpg',
                'Status' => 'available',
                'Location' => 'Downtown',
                'UserID' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '101 Maple Lane',
                'Type' => 'Apartment',
                'NumberOfRoom' => 2,
                'NumberOfToilet' => 1,
                'NumberOfBelcony' => 1,
                'Rent' => 1000,
                'Image' => 'house4.jpg',
                'Status' => 'available',
                'Location' => 'City Center',
                'UserID' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '202 Elm Street',
                'Type' => 'Townhouse',
                'NumberOfRoom' => 3,
                'NumberOfToilet' => 2,
                'NumberOfBelcony' => 1,
                'Rent' => 1800,
                'Image' => 'house5.jpg',
                'Status' => 'available',
                'Location' => 'Suburb',
                'UserID' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '303 Pine Avenue',
                'Type' => 'Condo',
                'NumberOfRoom' => 1,
                'NumberOfToilet' => 1,
                'NumberOfBelcony' => 0,
                'Rent' => 800,
                'Image' => 'house6.jpg',
                'Status' => 'available',
                'Location' => 'Downtown',
                'UserID' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '404 Cedar Lane',
                'Type' => 'House',
                'NumberOfRoom' => 5,
                'NumberOfToilet' => 4,
                'NumberOfBelcony' => 3,
                'Rent' => 2500,
                'Image' => 'house7.jpg',
                'Status' => 'available',
                'Location' => 'City Center',
                'UserID' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '202 Elm Street',
                'Type' => 'Townhouse',
                'NumberOfRoom' => 3,
                'NumberOfToilet' => 2,
                'NumberOfBelcony' => 1,
                'Rent' => 1800,
                'Image' => 'house5.jpg',
                'Status' => 'available',
                'Location' => 'Suburb',
                'UserID' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '303  amman',
                'Type' => 'Condo',
                'NumberOfRoom' => 1,
                'NumberOfToilet' => 1,
                'NumberOfBelcony' => 0,
                'Rent' => 800,
                'Image' => 'house6.jpg',
                'Status' => 'available',
                'Location' => 'Downtown',
                'UserID' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '404 ajlon',
                'Type' => 'House',
                'NumberOfRoom' => 5,
                'NumberOfToilet' => 4,
                'NumberOfBelcony' => 3,
                'Rent' => 2500,
                'Image' => 'house7.jpg',
                'Status' => 'available',
                'Location' => 'City Center',
                'UserID' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '202 Elm Street',
                'Type' => 'Townhouse',
                'NumberOfRoom' => 3,
                'NumberOfToilet' => 2,
                'NumberOfBelcony' => 1,
                'Rent' => 1800,
                'Image' => 'house5.jpg',
                'Status' => 'available',
                'Location' => 'marafq',
                'UserID' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '303 street  abdalla',
                'Type' => 'Condo',
                'NumberOfRoom' => 1,
                'NumberOfToilet' => 1,
                'NumberOfBelcony' => 0,
                'Rent' => 800,
                'Image' => 'house6.jpg',
                'Status' => 'available',
                'Location' => 'canad',
                'UserID' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '404 street Lane',
                'Type' => 'House',
                'NumberOfRoom' => 5,
                'NumberOfToilet' => 4,
                'NumberOfBelcony' => 3,
                'Rent' => 2500,
                'Image' => 'house7.jpg',
                'Status' => 'available',
                'Location' => 'City soth',
                'UserID' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '444 Elm Street',
                'Type' => 'Townhouse',
                'NumberOfRoom' => 3,
                'NumberOfToilet' => 2,
                'NumberOfBelcony' => 1,
                'Rent' => 1800,
                'Image' => 'house5.jpg',
                'Status' => 'available',
                'Location' => 'mdjjs',
                'UserID' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '200 Pine Avenue',
                'Type' => 'Condo',
                'NumberOfRoom' => 1,
                'NumberOfToilet' => 1,
                'NumberOfBelcony' => 0,
                'Rent' => 800,
                'Image' => 'house6.jpg',
                'Status' => 'available',
                'Location' => 'Downtown',
                'UserID' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Address' => '107 Cedar Lane',
                'Type' => 'House',
                'NumberOfRoom' => 5,
                'NumberOfToilet' => 4,
                'NumberOfBelcony' => 3,
                'Rent' => 2500,
                'Image' => 'house7.jpg',
                'Status' => 'available',
                'Location' => 'City Center',
                'UserID' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Output a message indicating that the seeder ran successfully
        $this->command->info('Houses table seeded successfully!');
    }
}
